# Generated by Django 5.0.7 on 2024-07-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'auto',
                'managed': False,
            },
        ),
    ]
